### ISSUE TITLE
other language locales

### ISSUE THREAD

**Issue by theofidry** [knopki/ansible-locale#5]
When I tried to set `locale_lang` to `fr_FR.UTF-8` it returned the error:

```
msg: The locales you've entered is not available on your system.
```

**Comment by jnv** [comment]
This may be an error in `locale_gen` module: https://github.com/ansible/ansible-modules-extras/issues/425 – if you're running Ubuntu, check if file `/etc/locale.gen` – removing the file should fix the problem.
